# version: 2.1

# orbs:
#   bridgecrew: bridgecrew/bridgecrew@1.0.5

version: 2.1
jobs:
  build:
    docker:
      - image: python:3.11

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install xmlsec
          command: |
            apt-get update
            apt-get install -y xmlsec1

      - run:
          name: Install dependencies
          command: python -m pip install --cache-dir ~/cache/pip -r requirements-dev.txt

      - save_cache:
          name: Save pip cache
          key: v1-staff-sso-{{ checksum "requirements-dev.txt" }}
          paths:
            - ~/cache/pip

      - run:
          name: Run tests
          command: python -m pytest --cov -s --junitxml=test-reports/junit.xml sso
          command: python -m checkov -d 

      - store_test_results:
          path: test-reports